### PR TITLE
Replace `Config` with explicit register types.

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by eldruin** [comment]
Do we need a higher MSRV?

**Comment by reitermarkus** [comment]
`const_panic` is in 1.57. I have replaced the `unreachable!` with a default match case instead for now.

**Comment by eldruin** [comment]
Uh, sorry but commit fc24b44 contains way too many fiddly changes for me to review. It will take me a while to go over it. A mitigation would be splitting into several commits, if that is something you would be willing to do.

**Comment by reitermarkus** [comment]
Sure, I'll try to split some of this out.

**Comment by reitermarkus** [comment]
I extracted some of this out into https://github.com/eldruin/lsm303agr-rs/pull/19.

**Comment by reitermarkus** [comment]
@eldruin I think this should be good to go now. Don't think I can split this further.

**Review by eldruin — APPROVED** [review]
Looks great, thank you for your work!

**Pull request merged**
