### PR TITLE
Combine setting mode and ODR functions.

### PR DESCRIPTION
**Pull request by reitermarkus**
Combine setting mode and ODR into one function so that we can properly determine the correct delay.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@eldruin, can you have a look at this? Thanks!

**Review by eldruin — COMMENTED** [review]
Thank you and sorry for the delay!
Would it be possible to add some tests for [these combinations](https://coveralls.io/builds/52363719/source?filename=src%2Faccel_mode_and_odr.rs#L112)?
Maybe also at least one test that calls [this function](https://coveralls.io/builds/52363719/source?filename=src%2Ftypes.rs#L328)?
Could you add an entry to the changelog and update the example code in the README as well?

**Comment by reitermarkus** [comment]
> Would it be possible to add some tests for [these combinations](https://coveralls.io/builds/52363719/source?filename=src%2Faccel_mode_and_odr.rs#L112)?

These are actually all tested, e.g. https://coveralls.io/builds/52363719/source?filename=src%2Faccel_mode_and_odr.rs#L205.

Added a changlog entry and a test covering the other function.

**Review by eldruin — APPROVED** [review]
Great work, thank you!

**Pull request merged**
