### PR TITLE
Allow changing magnetometer mode.

### PR DESCRIPTION
**Pull request by reitermarkus**
Also add necessary mode change delays.

### CODE REVIEW

**Comment by reitermarkus** [comment]
@eldruin, I think changing mode and ODR should be done in one function since the delay depends on both.

**Comment by eldruin** [comment]
> @eldruin, I think changing mode and ODR should be done in one function since the delay depends on both.

Yes, feel free to unite them. If it makes sense for this device, I'm all for it.

**Comment by reitermarkus** [comment]
@eldruin, can you merge this?

I think it's easier to unify in a follow-up PR.

**Review by eldruin — APPROVED** [review]
Sure, thank you!

**Pull request merged**
